---
- hosts: master
  vars_files:
    - defaults/main.yaml
  become: yes
  become_method: sudo
  roles:
   - master-keys
   - kube-master
   - kubectl
- hosts: workers
  vars_files:
    - defaults/main.yaml
  become: yes
  become_method: sudo
  roles:
    - worker-keys
    - kube-worker
