---
- name: create master keys directory
  file: name=/etc/kubernetes/ssl/ state=directory

- name: set up master TLS assets
  copy: src={{LOCAL_SSL_DIR}}/{{item}} dest=/etc/kubernetes/ssl/{{item}}
  with_items:
  - ca.pem
  - apiserver.pem
  - apiserver-key.pem
  - admin-key.pem
  - admin.pem
  - admin.csr
- file:
    path: /etc/kubernetes/ssl/apiserver-key.pem
    owner: root
    group: root
    mode: 600
